language: rust
sudo: false
cache:
  - cargo
rust:
  - stable
  - beta
  - nightly
env:
  - FEATURES=""
  - FEATURES="parallel"
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --all-targets --verbose --features=$FEATURES
  - cargo test --verbose --features=$FEATURES