[package]
name = "rkm"
version = "0.2.0"
authors = ["Nick Sarten <gen.battle@gmail.com>"]

[dependencies]
csv = "0.15.0"
rand = "0.3.15"
num = "0.1.37"
ndarray = "0.9.1"

[lib]
name = "rkm"
path = "src/lib.rs"

[[bin]]
name = "rkm_example"
path = "src/example.rs"

